name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: auxves/actions/deploy-minecraft-mod@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          java-version: 17
